name: dask36
channels:
- conda-forge
- bokeh
- defaults
dependencies:
- python>=3.6
- jupyter
- pandas
- tornado<4.5  # https://github.com/bokeh/bokeh/issues/6152
- bokeh
- dask
- distributed
- graphviz
- pip:
  - graphviz
  - pysenteishon
